services:
  privaxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: privaxy:local
    network_mode: bridge
    container_name: privaxy
    restart: unless-stopped
    environment:
      PRIVAXY_BIND_IP: 0.0.0.0
      PRIVAXY_WEB_BIND: 0.0.0.0:8110
      # Use this when you want Privaxy outbound traffic to go through another HTTP proxy.
      PRIVAXY_UPSTREAM_PROXY: http://192.168.0.111:8080
    ports:
      - "8100:8100"
      - "8110:8110"
    volumes:
      - ./privaxy-data:/root/.privaxy
  gost:
    image: ginuerzh/gost:latest
    container_name: gost
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    command:
      - "-L=http://:8080"
